# Generated by Django 2.2.7 on 2019-11-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodcut_options', models.CharField(choices=[('checking', 'CHECKING'), ('savings', 'SAVINGS'), ('debit', 'DEBIT'), ('credit', 'CREDIT')], default=('checking', 'CHECKING'), max_length=200)),
            ],
        ),
    ]
